## Importacion de Librerias y carga de Dataset

In [ ]:
%pip install pandas

import pandas as pd

In [5]:
df = pd.read_csv("ltrm_fish_data.csv", low_memory=False)

In [6]:
df.head()

,site,barcode,fstation,sitetype,stratum,sdate,stime,fdate,ftime,pool,...,grp_wdth,catch,weight,pathcode,subproj,userdef,recorder,nfsh_cnt,orphflag,batchno
0,NaN,11006939,1,1,BWC-S,06/18/2015,07:37,06/18/2015,07:52,04,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0,2710
1,NaN,11006939,1,1,BWC-S,06/18/2015,07:37,06/18/2015,07:52,04,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0,2710
2,NaN,11006939,1,1,BWC-S,06/18/2015,07:37,06/18/2015,07:52,04,...,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0,2710
3,NaN,11006939,1,1,BWC-S,06/18/2015,07:37,06/18/2015,07:52,04,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0,2710
4,NaN,11006939,1,1,BWC-S,06/18/2015,07:37,06/18/2015,07:52,04,...,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0,2710

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 466683 entries, 0 to 466682
Data columns (total 85 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   site      245410 non-null  str
 1   barcode   466683 non-null  int64
 2   fstation  466683 non-null  int64
 3   sitetype  466683 non-null  int64
 4   stratum   466683 non-null  str
 5   sdate     466683 non-null  str
 6   stime     466683 non-null  str
 7   fdate     463380 non-null  str
 8   ftime     463378 non-null  str
 9   pool      466683 non-null  str
 10  lcode     466683 non-null  str
 11  gear      466683 non-null  str
 12  period    466683 non-null  int64
 13  rep       0 non-null       float64
 14  summary   466683 non-null  float64
 15  project   466683 non-null  str
 16  effdist   244764 non-null  float64
 17  effhr     463282 non-null  float64
 18  effmin    463280 non-null  float64
 19  pwrgoal   235107 non-null  float64
 20  pwrused   235103 non-null  float64
 21  volts     235103 non-null  float64
 22  v_qf      0 non-null       float64
 23  amps      235103 non-null  float64
 24  a_qf      0 non-null       float64
 25  pulses    235127 non-null  float64
 26  p_qf      0 non-null       float64
 27  dutycyc   235101 non-null  float64
 28  dc_qf     0 non-null       float64
 29  utmzone   466361 non-null  float64
 30  utm_e     466683 non-null  int64
 31  utm_n     466683 non-null  int64
 32  gisgrid   77459 non-null   float64
 33  zone15e   448286 non-null  float64
 34  zone15n   448286 non-null  float64
 35  gpsmeth   466683 non-null  int64
 36  gpsacc    466683 non-null  float64
 37  secchi    461447 non-null  float64
 38  s_qf      45408 non-null   float64
 39  temp      463319 non-null  float64
 40  t_qf      28 non-null      float64
 41  depth     463370 non-null  float64
 42  d_qf      8154 non-null    float64
 43  cond      463136 non-null  float64
 44  c_qf      223 non-null     float64
 45  current   454823 non-null  float64
 46  cv_qf     12152 non-null   float64
 47  do        459156 non-null  float64
 48  do_qf     6726 non-null    float64
 49  stageht   0 non-null       float64
 50  sh_qf     0 non-null       float64
 51  sveg92    0 non-null       float64
 52  vegd      166245 non-null  float64
 53  eveg92    0 non-null       float64
 54  esveg92   453027 non-null  float64
 55  substrt   463342 non-null  float64
 56  snag      465500 non-null  float64
 57  wingdyke  455465 non-null  float64
 58  trib      455135 non-null  float64
 59  riprap    455135 non-null  float64
 60  inout     455125 non-null  float64
 61  closing   453302 non-null  float64
 62  flooded   453254 non-null  float64
 63  othrstrc  453254 non-null  float64
 64  labind    0 non-null       float64
 65  contanrs  466677 non-null  float64
 66  shtcnt    0 non-null       float64
 67  totfishc  463348 non-null  float64
 68  leader    0 non-null       float64
 69  pageno    463295 non-null  float64
 70  rec_site  463295 non-null  float64
 71  rownum    463327 non-null  float64
 72  fishcode  463327 non-null  str
 73  length    462156 non-null  float64
 74  tfs       462226 non-null  str
 75  grp_wdth  265015 non-null  float64
 76  catch     463327 non-null  float64
 77  weight    93101 non-null   float64
 78  pathcode  23231 non-null   str
 79  subproj   20101 non-null   str
 80  userdef   20100 non-null   str
 81  recorder  0 non-null       float64
 82  nfsh_cnt  0 non-null       float64
 83  orphflag  466683 non-null  int64
 84  batchno   466683 non-null  int64
dtypes: float64(61), int64(9), str(15)
memory usage: 302.6 MB

In [8]:
df.isnull().sum()

site        221273
barcode          0
fstation         0
sitetype         0
stratum          0
             ...
userdef     446583
recorder    466683
nfsh_cnt    466683
orphflag         0
batchno          0
Length: 85, dtype: int64

## Comenzamos a Limpiar Datos

In [9]:
# Eliminar Columnas Duplicadas 
df = df.drop_duplicates()

In [10]:
# Imprimir la lista de columnas enumeradas para encontrar la número 80 
# y decidir nuestras variables X (predictoras) y y (objetivo)
columnas = df.columns.tolist()
for i, col in enumerate(columnas):
    print(f"{i}: {col}")

0: site
1: barcode
2: fstation
3: sitetype
4: stratum
5: sdate
6: stime
7: fdate
8: ftime
9: pool
10: lcode
11: gear
12: period
13: rep
14: summary
15: project
16: effdist
17: effhr
18: effmin
19: pwrgoal
20: pwrused
21: volts
22: v_qf
23: amps
24: a_qf
25: pulses
26: p_qf
27: dutycyc
28: dc_qf
29: utmzone
30: utm_e
31: utm_n
32: gisgrid
33: zone15e
34: zone15n
35: gpsmeth
36: gpsacc
37: secchi
38: s_qf
39: temp
40: t_qf
41: depth
42: d_qf
43: cond
44: c_qf
45: current
46: cv_qf
47: do
48: do_qf
49: stageht
50: sh_qf
51: sveg92
52: vegd
53: eveg92
54: esveg92
55: substrt
56: snag
57: wingdyke
58: trib
59: riprap
60: inout
61: closing
62: flooded
63: othrstrc
64: labind
65: contanrs
66: shtcnt
67: totfishc
68: leader
69: pageno
70: rec_site
71: rownum
72: fishcode
73: length
74: tfs
75: grp_wdth
76: catch
77: weight
78: pathcode
79: subproj
80: userdef
81: recorder
82: nfsh_cnt
83: orphflag
84: batchno

In [11]:
# Columnas relevantes para el modelo
columnas_interes = ['fishcode', 'length', 'temp', 'depth', 'cond', 'do', 'secchi', 'weight']

In [12]:
# DataFrame nvo con columnas relevantes
df_modelo = df[columnas_interes].copy()

In [13]:
# Eliminar primera filas donde no existe el dato que queremos predecir
df_limpio = df_modelo.dropna(subset=['weight'])

In [14]:
# Eliminacion de las filas que tengan nulos características
df_limpio = df_limpio.dropna()

print(f"Filas útiles para los modelos (sin nulos): {len(df_limpio)}")

Filas útiles para los modelos (sin nulos): 92222

In [15]:
df_limpio.head()

    fishcode  length  temp  depth   cond   do  secchi  weight
648     LMBS   174.0  21.8    0.8  348.0  8.6    80.0    75.0
649     LMBS   124.0  21.8    0.8  348.0  8.6    80.0    29.0
650     BLGL   149.0  21.8    0.8  348.0  8.6    80.0    84.0
651     BLGL   165.0  21.8    0.8  348.0  8.6    80.0   119.0
652     BLGL   151.0  21.8    0.8  348.0  8.6    80.0    82.0

## Guardamos el Dataset Limpio con Fortamo CSV

In [17]:

df_limpio.to_csv("df_limpio.csv", index=False)